on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  linux:
    name: Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: xlcompose
      - name: Sh
        shell: sh -l {0}
        run: |
          conda info
          conda install pip pandas
          conda list
          pip install xlcompose
          pip install pytest
          pip install pytest-cov
    steps:
    - uses: actions/checkout@master
    - name: Generate coverage report
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: true
