- name: Install Miniconda
  shell: bash
  run: |
    if [[ "${{ runner.os }}" = "Linux" ]]; then
      MINICONDA_FILENAME=Miniconda3-latest-Linux-x86_64.sh
      curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
      bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
    elif [[ "${{ runner.os }}" = "macOS" ]]; then
      MINICONDA_FILENAME=Miniconda3-latest-MacOSX-x86_64.sh
      curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
      bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
    elif [[ "${{ runner.os }}" = "Windows" ]]; then
      MINICONDA_FILENAME=Miniconda3-latest-Windows-x86_64.exe
      curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
      ./Miniconda3-latest-Windows-x86_64.exe //InstallationType=JustMe //RegisterPython=0 //S
    fi

- name: Setup paths
  shell: bash
  run: |
    echo "::add-path::$HOME/miniconda3/bin"
    echo "::add-path::$HOME/miniconda3/Scripts"
